### ISSUE TITLE
Google login issues

### ISSUE THREAD

**Issue by Wolfy1995** [FalixNodes-Software/Mobile-App#1]
You can’t login using google on the app google says it wasn’t Authenticated with there servers or smt like that
![7B1E4980-D622-4691-86BE-6250C164AB03](https://user-images.githubusercontent.com/97574238/149054310-eda19c19-5447-4dd8-aa2c-906585199d1e.png)
![F469B486-4707-4C90-97BD-9E4103505304](https://user-images.githubusercontent.com/97574238/149054314-29124393-4063-4365-83a5-78b253f50f96.png)

**Comment by KorbsStudio** [comment]
Will be fixed in Alpha 7
