### ISSUE TITLE
Unable to download files from Game Panel (File Manager)

### ISSUE THREAD

**Issue by KorbsStudio** [FalixNodes-Software/Mobile-App#6]
In the game panel, users are unable to download files from the file manager. Even if the app has permissions to the device files. 

Proof:

https://user-images.githubusercontent.com/51213244/164268047-a4fcd9c8-22a9-45f6-b557-67dd41263baf.mp4

**Cause**
This may be caused by a permission error for the application.

**Comment by AgentDeath253** [comment]
Maybe make it open a browser to download the file(s)
